feat(SPV-1096): Improved View layout
BuxOrg/bux-console pull request #1037
Opened 2024-10-02 13:24 UTC by Nazarii-4chain

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet-admin/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet-admin/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-10-03 07:07 UTC, chris-4chain approved these changes

2024-10-04 15:08 UTC, chris-4chain requested changes

2024-10-04 15:08 UTC, chris-4chain commented on src/components/ViewDialog/ViewDialog.tsx
It looks weird on dark theme:
![image](https://github.com/user-attachments/assets/4b0f2b99-3427-44c6-a5da-3eeb8daf50cf)

Left-right scrolls unnecessarily appear.

The metadata box has to be polished...
![image](https://github.com/user-attachments/assets/c913e588-d495-45ba-9a02-5ecfa2defac4)

2024-10-07 09:31 UTC, Nazarii-4chain commented on src/components/ViewDialog/ViewDialog.tsx
Could you add your specs? I've checked on chrome, firefox and safari. It looks fine.

Firefox
![firefox](https://github.com/user-attachments/assets/99b317e5-3b4c-4c39-9f0b-e63e4ee87981)
Chrome
<img width="848" alt="chrome" src="https://github.com/user-attachments/assets/c870e8be-3961-4ca4-86f1-84da699f9a7c">
Safari
<img width="861" alt="safari" src="https://github.com/user-attachments/assets/d1dfac86-020c-49ac-aa74-e8cfa0e1bdd5">

2024-10-07 09:33 UTC, Nazarii-4chain commented on src/components/ViewDialog/ViewDialog.tsx
Metadata
<img width="771" alt="Metadata" src="https://github.com/user-attachments/assets/39df0251-837b-47d7-9fc3-96e301b9239c">

2024-10-07 11:17 UTC, chris-4chain commented on src/components/ViewDialog/ViewDialog.tsx
![image](https://github.com/user-attachments/assets/e51c3ab2-2d20-4602-a69f-fc4146432a6b)
![image](https://github.com/user-attachments/assets/4dc06b6f-2ded-4faf-944e-9cdc6bfc0a19)

2024-10-07 12:56 UTC, Nazarii-4chain commented on src/components/ViewDialog/ViewDialog.tsx
@chris-4chain try now

2024-10-09 07:27 UTC, chris-4chain requested changes

2024-10-09 07:27 UTC, chris-4chain commented on package.json
**More visual problems**
The JSON container weirdly changes its width on hover. 
![jumpyJson](https://github.com/user-attachments/assets/aef2cb63-9896-488c-b9af-a53d32b42199)

Additionally:
The HEX should be folded into multiple lines:
![image](https://github.com/user-attachments/assets/dee95feb-acff-4ce1-a80a-de608f73c2bf)

2024-10-09 07:47 UTC, Nazarii-4chain commented on package.json
It's only for hex field ? Because I've made these changes based on this

> Currently, when there is some long text for one line
then scroll (left-right) appears

2024-10-09 13:01 UTC, chris-4chain commented on package.json
Let's say, yes

2024-10-10 09:11 UTC, dzolt-4chain approved these changes

2024-10-15 05:30 UTC, chris-4chain approved these changes

2024-10-15 06:33 UTC, merged