feat(SPV-1107): remove delete option in deleted records
BuxOrg/bux-console pull request #1041
Opened 2024-10-15 13:13 UTC by Nazarii-4chain

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet-admin/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet-admin/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-10-16 09:22 UTC, dzolt-4chain approved these changes

2024-10-17 08:03 UTC, chris-4chain approved these changes

2024-10-17 08:13 UTC, chris-4chain requested changes

2024-10-17 08:13 UTC, chris-4chain commented on src/components/ContactsTabContent/ContactsTabContent.tsx
**After testing**

Please remove the `Delete` action button from all the views for `"Deleted"` records. 

E.g. for paymail (as admin) the button is still there. 
![image](https://github.com/user-attachments/assets/15b3ea86-27fa-49f6-973e-2a0378a6b8fe)

2024-10-17 09:47 UTC, Nazarii-4chain commented on src/components/ContactsTabContent/ContactsTabContent.tsx
You have delete option on each paymail? Please share details about paymails that have this option.

2024-10-18 09:57 UTC, chris-4chain commented on src/components/ContactsTabContent/ContactsTabContent.tsx
The problem was in a condition for `PaymailDeleteDialog`.
- show work now 👍

2024-10-18 10:22 UTC, chris-4chain approved these changes

2024-10-23 12:44 UTC, merged