feat(BUX-669): Removed transportType and changed README
BuxOrg/bux-console pull request #875
Opened 2024-03-16 09:03 UTC by Nazarii-4chain

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet-admin/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet-admin/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-03-29 10:08 UTC, chris-4chain commented on src/App.test.js
> +import { App } from './App.jsx';
Is the `.jsx` part necessary?

2024-04-02 08:28 UTC, Nazarii-4chain commented on src/App.test.js
> +import { App } from './App.jsx';
Removed

2024-04-03 06:13 UTC, chris-4chain approved these changes

2024-04-03 08:25 UTC, arkadiuszos4chain commented on src/pages/login.jsx
>                <>
Can we remove empty (`<>`) markups?

2024-04-03 08:30 UTC, arkadiuszos4chain commented
I don't understand the scope of the report that this PR is based on.

2024-04-10 09:53 UTC, Nazarii-4chain commented
> I don't understand the scope of the ticket that this PR is based on.

Edited Readme after renaming. Added proper links. Removed setTransport because we don't use it anymore. Updated dependnecy

2024-04-11 08:37 UTC, arkadiuszos4chain commented
Why did you add empty `pages/admin-login.jsx`?

2024-04-11 08:38 UTC, arkadiuszos4chain requested changes

2024-04-11 08:38 UTC, arkadiuszos4chain commented on src/pages/login.jsx
> +                  label={"http"}
remove '{' and '}'

2024-04-11 10:29 UTC, Nazarii-4chain commented
> Why did you add empty `pages/admin-login.jsx`?

Removed

2024-04-11 10:30 UTC, Nazarii-4chain commented on src/pages/login.jsx
> +                  label={"http"}
Removed

2024-04-11 11:26 UTC, arkadiuszos4chain approved these changes

2024-04-11 12:49 UTC, chris-4chain approved these changes

2024-04-12 13:45 UTC, merged